export enum Category {
  FINTECH = 'FinTech', // Financial Technology
  EDTECH = 'EdTech', // Education Technology
  HEALTHCARE = 'Healthcare', // Health and Medical Services
  ECOMMERCE = 'E-Commerce', // Online Retail and Shopping
  AI = 'Artificial Intelligence', // AI and Machine Learning
  IOT = 'Internet of Things', // Smart Devices and Connectivity
  AGRITECH = 'AgriTech', // Agriculture and Farming Technology
  GREENTECH = 'GreenTech', // Environmental and Clean Energy
  BIOTECH = 'BioTech', // Biotechnology and Life Sciences
  PROPTECH = 'PropTech', // Real Estate Technology
  SAAS = 'SaaS', // Software as a Service
  TRANSPORTATION = 'Transportation', // Mobility, Ride-sharing, Logistics
  CYBERSECURITY = 'Cybersecurity', // Security and Data Protection
  SOCIAL_MEDIA = 'Social Media', // Networking and Communication Platforms
  ENTERTAINMENT = 'Entertainment', // Media, Streaming, and Content Creation
  GAMING = 'Gaming', // Game Development and Esports
  MARKETING = 'Marketing', // Digital Marketing and AdTech
  HRTECH = 'HRTech', // Human Resources Technology
  LEGALTECH = 'LegalTech', // Law and Legal Services Technology
  SUPPLYCHAIN = 'Supply Chain', // Logistics and Supply Chain Management
  INSURTECH = 'InsurTech', // Insurance Technology
  FOODTECH = 'FoodTech', // Food and Beverage Innovation
  TRAVEL = 'Travel', // Travel and Tourism
  FASHION = 'Fashion', // Fashion and Apparel
  SPORTS = 'Sports', // Sports and Fitness
  FINANCIAL_SERVICES = 'Financial Services', // Banking, Investment, Wealth Management
  CONSTRUCTION = 'Construction', // Construction and Real Estate Development
  HARDWARE = 'Hardware', // Physical Devices and Gadgets
  NONPROFIT = 'Nonprofit', // Charitable and Non-Governmental Organizations
  OTHER = 'Other', // Miscellaneous or Unspecified
}
